# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobufs/smartlife.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protobufs/smartlife.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protobufs/smartlife.proto\x12\tsmartlife\"\x1f\n\rStatusRequest\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x1f\n\rActiveRequest\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\"\'\n\x11\x42rightnessRequest\x12\x12\n\nbrightness\x18\x01 \x01(\x05\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe4\x01\n\x0bStateUpdate\x12\x43\n\x0cStatusUpdate\x12\x18.smartlife.StatusRequest\x1a\x19.smartlife.UpdateResponse\x12\x43\n\x0c\x41\x63tiveUpdate\x12\x18.smartlife.ActiveRequest\x1a\x19.smartlife.UpdateResponse\x12K\n\x10\x42rightnessUpdate\x12\x1c.smartlife.BrightnessRequest\x1a\x19.smartlife.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.smartlife_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=40
  _globals['_STATUSREQUEST']._serialized_end=71
  _globals['_ACTIVEREQUEST']._serialized_start=73
  _globals['_ACTIVEREQUEST']._serialized_end=104
  _globals['_BRIGHTNESSREQUEST']._serialized_start=106
  _globals['_BRIGHTNESSREQUEST']._serialized_end=145
  _globals['_UPDATERESPONSE']._serialized_start=147
  _globals['_UPDATERESPONSE']._serialized_end=180
  _globals['_STATEUPDATE']._serialized_start=183
  _globals['_STATEUPDATE']._serialized_end=411
# @@protoc_insertion_point(module_scope)
